name: one_music_player
description: ONE Ultimate Offline Music Player
publish_to: 'none'
version: 1.0.0+1
environment:
sdk: '>=3.0.0 <4.0.0'
dependencies:
flutter:
sdk: flutter
cupertino_icons: ^1.0.2
just_audio: ^0.9.36
file_picker: ^8.0.0
flutter_equalizer: ^0.1.0
flutter_audio_waveforms: ^1.4.0
flutter_media_metadata: ^1.0.1
shared_preferences: ^2.2.3
dev_dependencies:
flutter_test:
sdk: flutter
flutter_lints: ^3.0.0
flutter:
uses-material-design: true
